app:
  build: .
  links:
    - postgres
  volumes:
    - ./:/application
    - ~/the/koa-resteasy:/koa-resteasy
  ports:
    - '80'
  command: bash -c "cp -r /koa-resteasy /koa-resteasy-local && npm link ../koa-resteasy-local && forever start sync_dir.js && nodemon server.js ; forever stopall"
  environment:
    - PREFIX=/package
    - 'DATABASE_URL=postgresql://pguser:pgpass@postgres:5432/sfez-development'
    - NODE_ENV=development
    - PORT=80
pgadmin:
  image: postgres:9.5
  command: tail -f /dev/null
  links:
    - postgres
  environment:
    - PGUSER=pguser
    - PGPASSWORD=pgpass
    - PGHOST=postgres
postgres:
  image: postgres:9.5
  environment:
    - POSTGRES_USER=pguser
    - POSTGRES_PASSWORD=pgpass
